# Generated by Django 5.2.17 on 2026-08-13 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=120)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='courts.venue')),
            ],
            options={
                'verbose_name': 'feriado',
                'verbose_name_plural': 'feriados',
            },
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('zone', models.CharField(choices=[('valle', 'Valle'), ('pico', 'Pico')], default='valle', max_length=8)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('court_type', models.CharField(blank=True, choices=[('techada', 'Techada'), ('abierta', 'Abierta')], max_length=10, null=True)),
                ('multiplier', models.DecimalField(decimal_places=3, max_digits=6)),
                ('priority', models.PositiveSmallIntegerField(default=10)),
                ('active', models.BooleanField(default=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='courts.venue')),
            ],
            options={
                'verbose_name': 'regla de precio',
                'verbose_name_plural': 'reglas de precio',
            },
        ),
    ]
