# Generated by Django 5.2.17 on 2026-09-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_courtschedule_chk_schedule_time_order'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('venue', 'date'), name='uniq_venue_holiday_date'),
        ),
    ]
