# Generated by Django 5.2.17 on 2026-08-13 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('stripe', 'Tarjeta'), ('transfer', 'Transferencia'), ('cash', 'Efectivo')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('authorized', 'Autorizado'), ('pending_transfer', 'Pendiente de transferencia'), ('captured', 'Capturado'), ('refunded', 'Reembolsado'), ('failed', 'Fallido'), ('confirmed', 'Confirmado')], default='pending', max_length=16)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=128)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
            },
        ),
    ]
