# Generated by Django 5.2.17 on 2026-08-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof_image',
            field=models.ImageField(blank=True, help_text='Foto del comprobante de transferencia bancaria', null=True, upload_to='transfer_proofs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Motivo de rechazo de transferencia (visible para el cliente)'),
        ),
    ]
