# Generated by Django 5.2.17 on 2026-08-13 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_windows', to='courts.court')),
            ],
            options={
                'verbose_name': 'mantenimiento',
                'verbose_name_plural': 'mantenimientos',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('booked', 'Reservado'), ('held', 'En espera'), ('blocked', 'Bloqueado')], default='available', max_length=12)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='courts.court')),
            ],
            options={
                'verbose_name': 'franja',
                'verbose_name_plural': 'franjas',
            },
        ),
        migrations.CreateModel(
            name='BookingHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.court')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='scheduling.timeslot')),
            ],
            options={
                'verbose_name': 'reserva temporal',
                'verbose_name_plural': 'reservas temporales',
            },
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('court', 'date', 'start'), name='uniq_court_date_start'),
        ),
    ]
