# Generated by Django 5.2.17 on 2026-09-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_courtschedule_chk_schedule_time_order'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ('date', 'start'), 'verbose_name': 'franja', 'verbose_name_plural': 'franjas'},
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['court', 'date', 'status'], name='idx_slot_court_date_status'),
        ),
        migrations.AddConstraint(
            model_name='maintenancewindow',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='chk_maintenance_time_order'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='chk_slot_time_order'),
        ),
    ]
