# Generated by Django 5.2.17 on 2026-08-13 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_window_hours', models.PositiveIntegerField(default=24)),
                ('penalty_ratio', models.DecimalField(decimal_places=2, default='0.50', max_digits=4)),
                ('no_show_ratio', models.DecimalField(decimal_places=2, default='1.00', max_digits=4)),
                ('hold_minutes', models.PositiveIntegerField(default=10)),
                ('active', models.BooleanField(default=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policies', to='courts.venue')),
            ],
            options={
                'verbose_name': 'politica de cancelacion',
                'verbose_name_plural': 'politicas de cancelacion',
            },
        ),
    ]
