# Generated by Django 5.2.17 on 2026-09-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_courtschedule_chk_schedule_time_order'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cancellationpolicy',
            constraint=models.UniqueConstraint(fields=('venue',), name='uniq_venue_cancellation_policy'),
        ),
    ]
