# Generated by Django 5.2.17 on 2026-09-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='courtschedule',
            constraint=models.CheckConstraint(condition=models.Q(('close_time__gt', models.F('open_time'))), name='chk_schedule_time_order'),
        ),
    ]
