# Generated by Django 5.2.14 on 2026-09-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0003_court_description_court_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_i18n", models.JSONField(blank=True, default=dict)),
                ("subtitle_i18n", models.JSONField(blank=True, default=dict)),
                ("image", models.ImageField(upload_to="banners/%Y/%m/")),
                ("link_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("none", "Sin enlace"),
                            ("url", "URL"),
                            ("whatsapp", "WhatsApp"),
                            ("event", "Evento"),
                        ],
                        default="none",
                        max_length=12,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "banner",
                "verbose_name_plural": "banners",
                "ordering": ("sort_order", "-created_at"),
            },
        ),
        migrations.AddField(
            model_name="venue",
            name="bank_account_code",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="venue",
            name="bank_account_holder",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="venue",
            name="bank_account_number",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="venue",
            name="bank_extra",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="venue",
            name="bank_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="venue",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="venue",
            name="home_greeting_tagline_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="venue",
            name="home_section_title_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="venue",
            name="instagram_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="venue",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="club/"),
        ),
        migrations.AddField(
            model_name="venue",
            name="maps_query",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="venue",
            name="maps_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="venue",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="venue",
            name="whatsapp_message",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="venue",
            name="whatsapp_number",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
